name: '$name'
version: '$version'
main: net.topstrix.hubinteractions.HubInteractionsPlugin
description: '$description'
api-version: '$apiVersion'
authors:
  - Gameoholic
depend: [ ProtocolLib ]
commands:
  test:
    description: Test
    usage: /test
  test2:
    description: Test2
    usage: /test2
  spawnfish:
    description: Spawns a fish in your current lake.
    usage: /spawnfish <variant_id?> <alive_time?> <fish_speed?>
  fishing:
    description: Opens the fishing menu.
    usage: /fishing