log-level: DEBUG

#General:
world:
  name: "world" #world used for cleaning up old fishing displays

#Fish rarities:
common-fish-minigame-min-direction-duration: 80
common-fish-minigame-max-direction-duration: 100
common-fish-minigame-speed: 0.2
common-fish-alive-time-min: 100
common-fish-alive-time-max: 200
common-fish-xp: 2
common-fish-display-name: "<gray>Common"
common-fish-crate-shard-chance: 0.005

rare-fish-fishes-required-to-spawn-min: 20 #20
rare-fish-fishes-required-to-spawn-max: 40 #40
rare-fish-minigame-min-direction-duration: 40
rare-fish-minigame-max-direction-duration: 60
rare-fish-minigame-speed: 0.4
rare-fish-alive-time-min: 100
rare-fish-alive-time-max: 200
rare-fish-xp: 10
rare-fish-display-name: "<blue>Rare"
rare-fish-crate-shard-chance: 0.0075

epic-fish-fishes-required-to-spawn-min: 150 #100
epic-fish-fishes-required-to-spawn-max: 300 #200
epic-fish-minigame-min-direction-duration: 20
epic-fish-minigame-max-direction-duration: 30
epic-fish-minigame-speed: 0.75
epic-fish-alive-time-min: 100
epic-fish-alive-time-max: 200
epic-fish-xp: 50
epic-fish-display-name: "<dark_purple>Epic"
epic-fish-crate-shard-chance: 0.1

legendary-fish-fishes-required-to-spawn-min: 500 #500
legendary-fish-fishes-required-to-spawn-max: 1500 #1000
legendary-fish-minigame-min-direction-duration: 5
legendary-fish-minigame-max-direction-duration: 30
legendary-fish-minigame-speed: 1.0
legendary-fish-alive-time-min: 100
legendary-fish-alive-time-max: 200
legendary-fish-xp: 200
legendary-fish-display-name: "<gold>Legendary"
legendary-fish-crate-shard-chance: 1.0

#Levels: 20/min. 200/ 10 min
level-initial-xp-requirement: 5
level-xp-requirement-growth: 5
level-xp-requirement-growth-cap: 10000
level-xp-requirement-growth-multiplier: 2.0
level-growth-delay: 5

# Rank boost:
rank-boost-permission: "ice"
rank-boost-amount: 2.0


# Gameplay settings:
water-area-start-position: 12.6 # Position from the right
water-area-length-pixels: 49.0 # Amount of pixels in which the fish & rodbox can move in
rod-box-speed: 0.8
max-fishing-rod-uses: 3

# Characters:
water-characters:
  - '༁'
  - '༂'
  - '༃'
  - '༄'
  - '༅'
  - '༆'
  - '༇'
  - '༈'
  - '༉'
  - '༊'
  - '་'
  - '༌'
  - '།'
  - '༎'
  - '༏'
  - '༐'
water-character-height: 15
water-animation-speed: 3 #How often the water animation frame updates. If set to 2, for example, will be animated every 2 frames.

rod-box-character: '्'
rod-box-character-height: 6

mini-rod-character: 'ॎ'
mini-rod-character-height: 6
mini-rod-animation-speed: 2
mini-rod-used-characters:
  - 'ᅀ'
  - 'ᅁ'
  - 'ᅂ'
mini-rods-characters-position: 48.0 # The position of the first mini fishing rod character, in UI pixels from the right

info-box-character: '༑'
info-box-character-height: 18
info-box-position: 79.5

big-rod-position: 84.0 #The position of the big fishing rod, in UI pixels from the right
big-rod-character-height: 20
big-rod-characters:
  - 'ॐ'
  - 'ॐ'
  - '॑'
  - '॑'
  - '॒'
  - '॒'
  - '॓'
  - '॓'
  #  - '੔' unused
  #  - '੔' unused
  - '॔'
  - '॔'
  - 'ॕ'
  - 'ॕ'
  #  - 'क़' #unduped Unused
  - 'ख़' #unduped


fishing-minigame-success-animation-length: 26
fishing-minigame-success-animation-speed: 2
bucket-character-height: 15
bucket-character-offset: 2.0 #By how many pixels to the left to offset the bucket relative to fish
bucket-characters:
  - '༒'
  - '༓'
  - '༔'
  - '༕'
  - '༖'
  - '༗'
  - '༘'
  - '༙' #this
  - '༚' #this
  - '༛'
  - '༜'
  - '༝'
  - '༞'

long-rod-character: 'ॖ'
long-rod-character-height: 10
long-rod-end-character: 'ॸ'
long-rod-end-character-height: 10
long-rod-end-character-offset: 4.5 #Since long rod end character longer than long rod character, we need to offset it to the left.

clock-animation-speed: 2
clock-character-height: 5
clock-characters:
  - 'ቀ'
  - 'ቁ'
  - 'ቂ'
  - 'ቃ'
  - 'ቄ'
  - 'ቅ'
  - 'ቆ'
  - 'ቇ'
clock-position: 35.0

extension-animation-delay: -1 #How long to delay before starting the extension animation. Can be set to negative values.
