log-level: DEBUG

#Fish rarities:
common-fish-minigame-min-direction-duration: 30
common-fish-minigame-max-direction-duration: 50
common-fish-minigame-speed: 0.3
common-fish-alive-time-min: 100
common-fish-alive-time-max: 200
common-fish-xp: 2
common-fish-display-name: "<gray>Common"
common-fish-crate-shard-chance: 0.005

rare-fish-fishes-required-to-spawn-min: 20 #20
rare-fish-fishes-required-to-spawn-max: 40 #40
rare-fish-minigame-min-direction-duration: 15
rare-fish-minigame-max-direction-duration: 25
rare-fish-minigame-speed: 0.6
rare-fish-alive-time-min: 100
rare-fish-alive-time-max: 200
rare-fish-xp: 5
rare-fish-display-name: "<blue>Rare"
rare-fish-crate-shard-chance: 0.01

epic-fish-fishes-required-to-spawn-min: 100 #100
epic-fish-fishes-required-to-spawn-max: 200 #200
epic-fish-minigame-min-direction-duration: 10
epic-fish-minigame-max-direction-duration: 20
epic-fish-minigame-speed: 1.0
epic-fish-alive-time-min: 100
epic-fish-alive-time-max: 200
epic-fish-xp: 30
epic-fish-display-name: "<dark_purple>Epic"
epic-fish-crate-shard-chance: 0.1

legendary-fish-fishes-required-to-spawn-min: 500 #500
legendary-fish-fishes-required-to-spawn-max: 1000 #1000
legendary-fish-minigame-min-direction-duration: 5
legendary-fish-minigame-max-direction-duration: 10
legendary-fish-minigame-speed: 1.3
legendary-fish-alive-time-min: 100
legendary-fish-alive-time-max: 200
legendary-fish-xp: 100
legendary-fish-display-name: "<gold>Legendary"
legendary-fish-crate-shard-chance: 1.0

#Gameplay settings:
water-amount: 7
rod-box-speed: 0.8
max-fishing-rod-uses: 3

#Characters:
water-character: 'ो'
water-character-height: 10

rod-box-character: '्'
rod-box-character-height: 6

mini-rod-character: 'ॎ'
mini-rod-character-height: 3

mini-rod-used-character: 'ॏ'
mini-rod-used-character-height: 3

big-rod-character-height: 10
big-rod-characters:
  - 'ॐ'
  - '॑'
  - '॒'
  - '॓'
  - '॔'
  - 'ॕ'

long-rod-character: 'ॖ'
long-rod-character-height: 10

#General:
world:
  name: "world" #world used for cleaning up old fishing displays
stats-display-content: "<White>Playtime: <playtime><br><red>Level: <level>. To level up: <xp>/<total_xp_to_level_up> (<remaining_xp_to_level_up>)<br><white>Fishes Caught: <fishes_caught><br><common_fishes_caught> <rare_fishes_caught> <epic_fishes_caught> <legendary_fishes_caught>" #xp, total_xp, total_xp_to_level_up, level, remaining_xp_to_level_up, playtime, fishes_caught, common_fishes_caught, rare_fishes_caught, epic_fishes_caught, legendary_fishes_caught
rank-boost-permission: "ice"
rank-boost-display-none-content: "<aqua>The lake is currently <red>not</red> boosted.<br>Purchase <bold>ICE</bold> to boost the chances of spawning rare fish by 3x!"
rank-boost-display-boosted-content: "<aqua>Boosted by <bold><player></bold>.<br>Rare fish spawn chances are increased by <bold><red>3x."
rank-boost-amount: 3

#Levels: 20/min. 200/ 10 min
level-initial-xp-requirement: 5
level-xp-requirement-growth: 5
level-xp-requirement-growth-cap: 10000
level-xp-requirement-growth-multiplier: 2.0
level-growth-delay: 5